---
title: Laravelで作ったブログをHerokuで公開する
description: Laravelで作ったブログをHerokuで公開するまでの手順の解説です。
date: 2014-11-16
updated: 2015-05-28
tags: PHP, Laravel, heroku
---

どこかのPaaSにLaravelで作ったブログを公開したかったので、使用するPaaSの条件をいくつか考えてみました。

* Laravel(PHP)が使用できること
* 無料で使用できること
* 独自ドメインが使用できること
* データベースがPostgreSQLもしくはMySQL

これらを条件にすると残る自分の知っているPaaSで、以前であればlink:https://heroku.com/[Heroku]があったのですが、現在HerokuのFreeプランではこの条件に合致しなくなっています。Freeの場合一日に数時間のsleepが必要になるため、今回のようなブログ用途には不向きです。今であれば無料が前提であるならば、link:https://www.openshift.com/[OpenShift]あたりになるとおもいます。

今回は当時使っていたherokuにLaravel製のブログをアップロードする方法の解説です。

[IMPORTANT]
.hbsnow-sandbox/blog-laravel5
https://github.com/hbsnow-sandbox/blog-laravel5



[[install]]
== インストール

https://devcenter.heroku.com/articles/getting-started-with-php[Getting Started with PHP on Heroku]をある程度すすめていき、アカウント作成とToolbeltのダウンロードとインストールします。Windowsを使っていたのでlink:https://chocolatey.org/packages/heroku-toolbelt[chocolatey]を使おうとしたんだけど、残念ながらパッケージのメンテナンスはされてなかったので素直に公式からダウンロード。インストール後はなんとなく不安だったので再起動。



[[ssh-key]]
== SSHの公開鍵の設定

公開鍵を作成します。

[source,ps1]
----
cd ~/.ssh
ssh-keygen -t rsa
----

これでSSH Keyが作成されます。

[source,ps1]
----
heroku login
----

指示に従っていけば先ほど作成したSSHの公開鍵が登録されます。今回は他にSSH Keyが何もないPCで作成したのでとくに設定することはなかったんだけど、他にSSH Keyがあるとまた別に設定が必要になるかも。



[[create-app]]
== App作成とLaravelの設定変更

Laravelの必要な場所を変更する前にまずAppを作成します。これを先にやってしまわないとURLの記述の変更ができません。

[source,ps1]
----
git init
heroku create Appの名前
----

Appの作成をダッシュボードで確認して、ついでにデータベースを作成します。データベースはHobby-devという無料プランを選択。

これでLaravelの設定変更に必要な情報が揃ったので、設定を書き換えることができるようになりました。使用しているLaravelの設定を変更しましょう。

Laravel4では`.gitignore`に`composer.lock`が含まれているので削除しておきます。またドキュメントのルートを変更するためにプロジェクト直下に`Procfile`というファイルを追加して、以下の内容を追記しておきます。

[source]
----
web: vendor/bin/heroku-php-apache2 public
----



[[deploy]]
== 公開

[source,ps1]
----
git add . -A
git commit -m "first commit"
git push heroku master
----

あとはローカルと同じようにマイグレーションとシーディングを実行します。ついでにタイムゾーンも日本のものに変更しました。

[source,ps1]
----
heroku config:add TZ=Asia/Tokyo
heroku run php artisan migrate
heroku run php db:seed
----



[[domain]]
== 独自ドメイン

独自ドメインを使いたいのでその設定をします。ドメインはValue Domainを使っているけれども、他のサービスでもやることはあまり変わらないはず。

ただしHerokuでルートドメインを使用するためにはひとてま必要で、他のサービスを併用するかlink:https://addons.heroku.com/zerigo_dns[有料アドオン]を使う必要があります。

まずはHerokuにドメインを登録しておきます。

[source,ps1]
----
heroku domains:add ドメイン
----

これで登録されてるのかとおもったけど、後になってダッシュボードを確認してみると追加されていなかったのでダッシュボードでも追加しておいた。ただダッシュボードだけで追加してもどうやら反映はされない、もしくはすぐされないようなのでコマンドも入力しておいたほうがいい。



[[cloudflare]]
=== CloudFlare

他サービスを使ってルートドメインを使用するためにはApex Aliasを使う必要があるためValue Domainだけでは対応できません。そのためlink:https://www.cloudflare.com/[CloudFlare]のようなサービスを使用する必要があります。

設定方法はCloudFlareでルートドメインにCNAMEを割り当てるだけです。CloudFlareで設定が終ったあとは`Appの名前.herokuapp.com`のアクセスを転送するため、`.htaccess`に以下の内容を追記しました。

[source]
----
RewriteCond %{HTTP_HOST} ^xxx.herokuapp.com$
RewriteRule (.*) http://example.com/$1 [R=301,L]
----



[[laravel5-deploy-error]]
== Laravel5をデブロイしたときに発生するエラー

Laravel5をとくに設定を変更せずそのままデブロイしようとするとエラーが発生します。これは`package.json`があるとアプリケーションがNode.jsであると判別されるせいです。

[source,ps1]
----
heroku config:set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php
----

PHPと認識させるためにはBuildpackをPHPに変更する必要があります。



[[bibliography]]
== 参照文献

[bibliography]
* https://devcenter.heroku.com/articles/getting-started-with-php[Getting Started with PHP on Heroku | Heroku Dev Center]
* http://qiita.com/Tkashiro/items/8249455477bbb5333118[Express - herokuにルートドメインを無料で設定する - Qiita]
* http://d.hatena.ne.jp/kitokitoki/20130127/p2[Heroku で日付時刻の表示(9時間ずれて表示される問題の対処) - わからん]
* http://qiita.com/mm36/items/343e23b60a5795997e88[Laravel5 を Heroku にデプロイ]
