---
title: LalavelからサービスアカウントでGoogle Driveのファイル情報を取得する
date: 2015-03-18
updated: 2015-04-13
tags: PHP, Laravel
---

https://github.com/hbsnow/laravel5-blog[以前ののブログ]はすべてGoogle Driveで、記事ごとによるディレクトリ単位で管理されていました。例えばこの記事だと`root\public\4uing\blog\LalavelからGoogle Driveのファイル情報を取得する`にある`index.md`、ここでは使われていないけれど記事内に画像などがあれば、それらのファイルも当然そのディレクトリに含まれることになります。

これまで`index.md`の呼び出しは、単純に以下のように行っていました。

[source,php]
----
file_get_contents('https://drive.google.com/uc?export=view&id=' . $file_id);
----

ファイルの内容だけ欲しいときはこれでもいいんだけど、更新についての情報だったりタイトルになる親のディレクトリ名や最終更新日時などを取得できるわけではないので、それらを取得するためには以下の方法をとる必要があります。

- データベースに保存しておく
- Google Drive APIを使ってその都度データを取得する

すべてのデータをデータベースに保存しておいてももちろん問題ないんだけど、自分はMarkdownのファイル内にはメタデータを記述したくなかったので結局データベースに保存するにもGoogle Drive APIでデータを取得する必要がありました。



[[install]]
== ライブラリのインストール

Google APIにアクセスするためのライブラリを`composer require google/apiclient`でインストールします。

githubではgoogle-api-php-clientなんだけどpackegistではapiclientになっているので、packegistで検索してもなかなか見つけられないと思う、自分がそうだった。

あとはautoloadに以下を追加して`composer update`。

[source,json]
----
"autoload": {
  "classmap": [
    ...
    "vendor/google/apiclient/src/Google"
  ],
}
----



[[drive-api]]
== Drive API

情報を取得するにはDrive APIを利用する必要があります。link:https://console.developers.google.com/[Google Developers Console]のAPIと認証からDrive APIを有効にします。

認証のOAuthで新しいクライアントIDを作成します。今回の目的はユーザに認証を求めるようなウェブアプリケーションではないので、サービスアカウントを作ることになります。キーが発行されるので、発行された`.p12`を適当なフォルダに移動します。自分の場合は`resources\assets\`にしました。



[[class]]
== クラスの作成

Google Driveにアクセスするためのクラスを作成します。link:https://laracasts.com/discuss/channels/tips/google-api-service-account-connection-laravel-5[Google カレンダーでのコード]があったのでほとんどそのまま使わせてもらいました。

[source,php]
----
class GoogleDrive
{
    protected $service;
    protected $file;

    /**
     * コンストラクタ
     *
     * @param $file_id 読み込むファイルのID
     */
    function __construct($file_id)
    {
        $service_account_name = 'XXX@developer.gserviceaccount.com';
        $key_file_location = base_path() . '/resources/assets/XXX.p12';

        $client = new \Google_Client();
        $this->service = new \Google_Service_Drive($client);

        if (Cache::has('service_token'))
        {
            $client->setAccessToken(Cache::get('service_token'));
        }

        $key = file_get_contents($key_file_location);
        $scopes = ['https://www.googleapis.com/auth/drive'];

        $auth = new \Google_Auth_AssertionCredentials($service_account_name, $scopes, $key);

        $client->setAssertionCredentials($auth);

        if ($client->getAuth()->isAccessTokenExpired())
        {
            $client->getAuth()->refreshTokenWithAssertion($auth);
        }

        Cache::forever('service_token', $client->getAccessToken());

        $this->file = $this->service->files->get($file_id);
    }
}
----

あとは使いそうなメソッドを適当に追加していけばいいんだけど、ドキュメントがなんかなさそうなので結構コードをみながら作らないといけないのでわりと面倒でした。やりたいことを検索しても一年前の情報ですら参考にならなかったりするので結構大変。




[[caution]]
== 注意すべきこと

気をつけなければいけないのは、サービスアカウントを使ったログインではそのサービスアカウントで作成したファイルのリストしか取得できないということ。

[source,php]
----
public function getFileList($folder_id)
{
    $children = $this->service->children->listChildren($folder_id);

    return $children->getItems();
}
----

例えばこのようなメソッドは、認証済みの自分のGoogle Driveの子フォルダを含むフォルダのIDを指定しても、その子フォルダがすべてアプリケーションで作成したものでないなら、空の配列が返されることになります。

リストが取得できないというだけで、親フォルダのディレクトリ名のようなものであれば取得できます。

[source,php]
----
public function getTitle($file_id)
{
    $results = $this->service->files->get($file_id);
    $parent_id = $results->parents[0]->getID();

    return $this->service->files->get($parent_id)->getTitle();
}
----

ただどうしてこれが取得できるのかは正直ちょっとよくわからない、どこかに書いてそうではあるけど。そもそも`$results->parents`で取得できるのは本来親フォルダの所属するディレクトリの全ファイルっぽい感じのところが、実際に取得できているのが親フォルダだけなので、親のディレクトリだけは参照できるということなのかもしれない。



[[bibliography]]
== 参照文献

[bibliography]
- https://developers.google.com/api-client-library/php/start/installation[Installation - Google APIs Client Library for PHP &mdash; Google Developers]
- https://laracasts.com/discuss/channels/tips/google-api-service-account-connection-laravel-5[Google API - Service account connection - Laravel 5]
